# Directory to copy files and subdirectories from
src = '~/music/'
# If dst is not specified, . (current directory) is used
dst = '~/transcode/'

# settings control the behaviour of the tool, defaults are listed below
[settings]
# whether to delete files/directories from dst that are not present in src
delete_removed = false
# whether to copy files not matching any rules as-is
copy_unmatched = true
# whether paths not matching any filters are automatically excluded
exclude_by_default = false
# whether to preserve config file even if delete_removed is true
preserve_config_file = true

# Fitlers are used to exclude directories or files from processing.
# Depeding on the value of exclude_by_default, they can also be used
# to selectively include only what you need.
[[filter]]
# Name of every file/directory is matched against this regex,
# directory names have / appended to distinguish them from files.
# If a directory is excluded, all its contents are excluded as well.
exclude = '^unsorted/$'

[[filter]]
# Filters are processed in order, the first filter to match wins.
# You can use "include" filters to overwrite more broad "exclude" filters.
include = '^README\.txt$'

[[filter]]
# This will not match README.txt (see above).
exclude = '^.*\.(txt|log)$'

[[rename]]
# Renames are applied after filters, but before transcoding rules.
# This one makes paths compatible with android by removing "special" characters.
pattern = '[\?\*:"]'
replacement = '_'

# Rules are matched against filenames post rename, first matched rule is applied.
[[rule]]
# Capture groups can be used, see https://pkg.go.dev/regexp#Regexp.Expand
src = '^(.*)\.(png|jpg)'
dst = '${1}.jpg'
# Command is specified as argument list, values @SRC@ and @DST@ are replaced
# with source and destination file paths respectively.
cmd = [ 'magick', '@SRC@', '-resize', '512x512>', '@DST@' ]

[[rule]]
src = '^(.*)\.flac$'
dst = '${1}.opus'
# Command can also be specified as a string, in which case it is passed to
# /bin/sh with source and destination file paths as positional arguments.
cmd = 'ffmpeg -y -loglevel error -i "$1" "$2"'
# The above is equivalent to:
# cmd = [ '/bin/sh', '-c', 'ffmpeg -y -loglevel error -i "$1" "$2"', 'sh', '@SRC@', '@DST@' ]

